post_install() {
	echo ">>> Remember to launch vgmplay with your sound system's OSS wrapper if you are not using OSS."
	echo "    The launcher checks for pulseaudio and launches with padsp if running."
	echo '>>> To configure vgmplay, copy /usr/share/vgmplay/VGMPlay.ini to $XDG_CONFIG_HOME/vgmplay/VGMPlay.ini'
	echo '    (typically ~/.config/vgmplay/VGMPlay.ini) and edit the file.  vgmplay accepts no -options.'
}
