#!/usr/bin/env bash

_vgmplay_help() {
cat <<EOF
Usage: vgmplay [options] filename
Plays VGM, VGZ, CMF, and DRO files either singly or by m3u playlist.

Options:
 -h, -?, --help               display this help and exit
 -c <file>,
         --config=<file>      load alternate config file (VGMPlay.ini)

 -p,     --padsp              force use of padsp (PulseAudio's OSS wrapper)
 -s <server>,
         --paserver=<server>  set alternate PulseAudio server (implies --padsp)
 -a,     --aoss               force use of aoss (ALSA's OSS wrapper)
 -o,     --oss                force use of OSS (native OSS, ossp)

         --version            display VGMPlay and VGM Format versions and exit

Keys (In-Player):
 Left/Right                   Seek 5 seconds backward/forward
 Ctrl + Left/Right            Seek 60 seconds backward/forward
 Space                        Pause
 Escape twice                 Quit Program
 F                            Fade Out Current Track   
 R                            Restart Current Track
 PageUp/B                     Previous Track (in playlist)
 PageDown/N                   Next Track (in playlist)
EOF
}


